# Generated by Django 2.1.7 on 2019-03-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publish_date', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('blogs_body', models.CharField(max_length=500)),
            ],
        ),
    ]
